# SITE CONFIGURATION
baseurl: ""
url: "https://sbasischeck.github.io"
title: sbasischeck– stay in Wonderland! # site's title
description: "My Site"      # used by search engines

defaults:
  - scope:
      path: "" # an empty string here means all necessary files are in the project
    values:
      image: assets/img/background/book-glass.jpeg

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  avatar: assets/img/sbasischeck.png
  color_image: /assets/img/lineart.png # In post when you set color
  favicon: assets/favicon.ico

  # Header and footer text
  header_text: sbasischeck<br>take the red pill – you stay in Wonderland!  # Change Blog header text
  header_feature_image: assets/img/background/matrix.jpg
  footer_text: >
    Follow the white rabbit!

  # Blog
  excerpt: true # Or "truncate" (first 250 characters), "false" to disable

  # Icons
  rss: true  # Make sure you created a feed.xml with feed.xml layout
  email_address: sbasicheck@gmail.com # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab: "sbasischeck"
  github: "sbasischeck"
  instagram:
  keybase:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_overflow:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "sbasischeck"
  vimeo:
  wordpress:
  youtube: "sbasischeck"

  # Sharing options
  share_buttons:
    facebook:
    twitter: true
    tumblr:
    pinterest:
    pocket:
    reddit:
    linkedin:
    wordpress:
    email: true

  # Scripts / Features 
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_share_on: "Share on"
  str_add_to: "Add to"
  str_email: "Email"
  str_tweet: "Tweet"
  str_pin_it: "Pin it"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."

  # Post navigation
  post_navigation: true

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PAGINATION
paginate: 20
paginate_path: "blog/page:num"

# AUTHORS
authors:
  sbasischeck: # author-id
    name: "Roland Knipp"
    avatar: "assets/img/avatars/sbasischeck.png"
    url: https://twitter.com/sbasischeck

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name
  microworld:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag]
exclude: [".jekyll-cache", "Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", ".idea",
          "LICENSE", "README.md", "screenshot.png", "assets/package.json", "assets/node_modules", 
          "assets/gulpfile.js", "starter.sh", "updater.sh"]

# theme: type-on-strap # Uncomment if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap # If using as a remote_theme in github
